openapi: 3.0.0
info:
  title: Data Plugin
  description: A plugin that manages data.
  version: 1.0.0
paths:
  /data:
    get:
      operationId: getData
      summary: Get the data.
      responses:
        '200':
          description: The current data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The data.
    post:
      operationId: postData
      summary: Update the data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: The updated data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The data.
    put:
      operationId: putData
      summary: Replace the data.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: The replaced data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The data.
    delete:
      operationId: deleteData
      summary: Delete the data.
      responses:
        '200':
          description: The deleted data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: The data.
